### ISSUE TITLE
Inner filter?

### ISSUE THREAD

**Issue by Selfie-bd** [PR0FESS0R-99/LuciferMoringstar-Robot#17]
How can do Internal filter?

**Comment by Githubbotof** [comment]
BEST BOT EVER

**Comment by Selfie-bd** [comment]
> BEST BOT EVER

Internal filter? 

Not /filter command

How to add filter in bot db.... Like if seach money heist in Any group it will show my filter

**Comment by PR0FESS0R-99** [comment]
🤷‍♂️
